"""
SatQuery AI - Optical / SAR Analysis Tools.

Real-data analysis adapters for:
    1. OpticalSARFusionModel
    2. WaterBodyDetectionTool
    3. BuiltUpAreaDetectionTool

The module accepts observations produced by raster_ingestor.py.  In particular,
the observation may contain:
    - file_path / local_path
    - band_map with per-band asset paths
    - analysis_asset pointing to a canonical multispectral GeoTIFF
    - assets / ingestion_manifest
    - direct numpy arrays

No scientific result or calibrated confidence is fabricated.
"""

from __future__ import annotations

import os
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np

from app.models.base_model import BaseRSModel

try:
    import rasterio
    from rasterio.enums import Resampling
except ImportError:  # pragma: no cover
    rasterio = None
    Resampling = None


# ============================================================
# UTILITY FUNCTIONS
# ============================================================


def _normalize_confidence(value: Any) -> float:
    """
    Normalize a supplied confidence into [0, 1].

    None / missing confidence is represented as 0.0 so callers never mistake
    the absence of a calibration value for a measured confidence.
    """
    if value is None:
        return 0.0

    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return 0.0

    if numeric > 1.0:
        numeric /= 100.0

    return max(0.0, min(1.0, numeric))


def _safe_percentage(mask: np.ndarray) -> float:
    mask = np.asarray(mask)
    if mask.size == 0:
        return 0.0
    return float(np.count_nonzero(mask) / mask.size * 100.0)


def _finite_values(array: np.ndarray) -> np.ndarray:
    values = np.asarray(array, dtype=np.float32)
    return values[np.isfinite(values)]


def _safe_statistics(array: np.ndarray) -> Dict[str, Optional[float]]:
    values = _finite_values(array)

    if values.size == 0:
        return {"min": None, "max": None, "mean": None}

    return {
        "min": float(np.min(values)),
        "max": float(np.max(values)),
        "mean": float(np.mean(values)),
    }


def _get_modality(image: Dict[str, Any]) -> str:
    return str(image.get("modality", "") or "").strip().lower()


def _is_optical(image: Dict[str, Any]) -> bool:
    modality = _get_modality(image)
    return "optical" in modality or "multispectral" in modality


def _is_sar(image: Dict[str, Any]) -> bool:
    modality = _get_modality(image)
    return "sar" in modality or "radar" in modality


def _get_image_source(image: Dict[str, Any]) -> Any:
    """
    Resolve an observation-level raster source.

    A semantic band may have its own path in band_map; those paths are resolved
    separately by _read_semantic_band().
    """
    for key in (
        "file_path",
        "filePath",
        "local_path",
        "localPath",
        "image_path",
        "path",
        "raster",
    ):
        value = image.get(key)
        if value is not None and str(value).strip():
            return value

    raise ValueError(
        "Observation does not contain an accessible raster source."
    )


# ============================================================
# RASTER READING
# ============================================================


def _coerce_band_value(value: Any) -> Any:
    if isinstance(value, dict):
        return (
            value.get("index")
            or value.get("band")
            or value.get("band_index")
            or value.get("path")
        )
    return value


def _extract_band_map(
    image: Dict[str, Any],
    metadata: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Read the semantic band map generated by raster_ingestor.py.
    """
    candidates = (
        image.get("band_map"),
        image.get("metadata", {}).get("band_map")
        if isinstance(image.get("metadata"), dict)
        else None,
        image.get("product_metadata", {}).get("band_map")
        if isinstance(image.get("product_metadata"), dict)
        else None,
        metadata.get("band_map"),
    )

    for candidate in candidates:
        if isinstance(candidate, dict):
            return candidate

    return {}


def _resolve_semantic_asset_path(
    image: Dict[str, Any],
    metadata: Dict[str, Any],
    band_name: str,
) -> Optional[str]:
    """
    Resolve a semantic band to its actual raster file path.

    raster_ingestor.py stores:
        band_map["green"]["path"]
    etc.
    """
    band_map = _extract_band_map(image, metadata)
    value = band_map.get(band_name)

    if isinstance(value, dict):
        path = value.get("path")
        if path:
            return str(path)

    if isinstance(value, str):
        # A string may itself be a path.
        candidate = Path(value)
        if candidate.exists():
            return str(candidate)

    # Flat compatibility keys.
    for key in (
        band_name,
        f"{band_name}_path",
        f"{band_name}Path",
    ):
        value = image.get(key)
        if isinstance(value, str) and value.strip():
            path = Path(value)
            if path.exists():
                return str(path)

    return None


def _get_band_index(
    image: Dict[str, Any],
    metadata: Dict[str, Any],
    band_name: str,
) -> Optional[int]:
    band_map = _extract_band_map(image, metadata)
    value = band_map.get(band_name)

    if isinstance(value, list):
        if not value:
            return None
        value = value[0]

    value = _coerce_band_value(value)

    # Do not interpret a file path as a numeric raster index.
    if isinstance(value, str) and not value.strip().isdigit():
        return None

    try:
        index = int(value)
    except (TypeError, ValueError):
        return None

    return index if index >= 1 else None


def _read_single_band_file(path: str) -> Tuple[np.ndarray, Dict[str, Any]]:
    if rasterio is None:
        raise RuntimeError(
            "Rasterio is required to read GeoTIFF/JP2 remote-sensing data."
        )

    source_path = Path(path)

    if not source_path.exists() or not source_path.is_file():
        raise FileNotFoundError(f"Raster asset not found: {source_path}")

    with rasterio.open(source_path) as src:
        if src.count < 1:
            raise ValueError(f"Raster contains no bands: {source_path}")

        array = src.read(1, out_dtype="float32")
        profile = {
            "driver": src.driver,
            "width": src.width,
            "height": src.height,
            "count": src.count,
            "dtype": "float32",
            "crs": src.crs.to_string() if src.crs else None,
            "transform": src.transform,
            "bounds": src.bounds,
            "nodata": src.nodata,
            "descriptions": src.descriptions,
            "path": str(source_path),
        }

    return array, profile


def _read_semantic_band(
    image: Dict[str, Any],
    metadata: Dict[str, Any],
    band_name: str,
) -> np.ndarray:
    """
    Read one real semantic band.

    Priority:
      1. image["bands"][band_name] numpy array
      2. actual path from image["band_map"][band_name]["path"]
      3. canonical multi-band GeoTIFF via band_map numeric index
      4. descriptive fallback index mapping
    """
    direct_bands = image.get("bands")

    if isinstance(direct_bands, dict) and band_name in direct_bands:
        direct = np.asarray(
            direct_bands[band_name],
            dtype=np.float32,
        )
        if direct.ndim != 2:
            raise ValueError(
                f"Band '{band_name}' must be a 2-D array."
            )
        return direct

    direct_path = _resolve_semantic_asset_path(
        image,
        metadata,
        band_name,
    )

    if direct_path:
        array, _ = _read_single_band_file(direct_path)
        return array

    index = _get_band_index(
        image,
        metadata,
        band_name,
    )

    if index is None:
        raise ValueError(
            f"Semantic band '{band_name}' is unavailable in the observation."
        )

    source = _get_image_source(image)

    if not isinstance(source, (str, Path)):
        raise ValueError(
            f"Band '{band_name}' has an index mapping but no file source exists."
        )

    source_path = Path(source)

    if not source_path.exists():
        raise FileNotFoundError(f"Raster file not found: {source_path}")

    if rasterio is None:
        raise RuntimeError(
            "Rasterio is required to read raster bands."
        )

    with rasterio.open(source_path) as src:
        if index > src.count:
            raise ValueError(
                f"Band '{band_name}' maps to raster band {index}, "
                f"but the raster only contains {src.count} bands."
            )

        return src.read(index, out_dtype="float32")


def _read_semantic_band_with_profile(
    image: Dict[str, Any],
    metadata: Dict[str, Any],
    band_name: str,
) -> Tuple[np.ndarray, Dict[str, Any]]:
    """
    Same as _read_semantic_band(), but also returns geospatial metadata.
    """
    direct_bands = image.get("bands")
    if isinstance(direct_bands, dict) and band_name in direct_bands:
        array = np.asarray(direct_bands[band_name], dtype=np.float32)
        if array.ndim != 2:
            raise ValueError(f"Band '{band_name}' must be 2-D.")
        return array, {}

    direct_path = _resolve_semantic_asset_path(
        image,
        metadata,
        band_name,
    )

    if direct_path:
        return _read_single_band_file(direct_path)

    index = _get_band_index(image, metadata, band_name)
    source = _get_image_source(image)

    if index is None:
        raise ValueError(
            f"Semantic band '{band_name}' is unavailable in the observation."
        )

    if not isinstance(source, (str, Path)):
        raise ValueError(
            f"Band '{band_name}' has an index but source is not a file."
        )

    if rasterio is None:
        raise RuntimeError("Rasterio is required to read raster bands.")

    with rasterio.open(source) as src:
        if index > src.count:
            raise ValueError(
                f"Band '{band_name}' maps to band {index}, "
                f"but source contains {src.count} bands."
            )

        array = src.read(index, out_dtype="float32")
        profile = {
            "driver": src.driver,
            "width": src.width,
            "height": src.height,
            "count": src.count,
            "dtype": "float32",
            "crs": src.crs.to_string() if src.crs else None,
            "transform": src.transform,
            "bounds": src.bounds,
            "nodata": src.nodata,
            "descriptions": src.descriptions,
            "path": str(Path(source)),
        }
        return array, profile


def _get_valid_data_mask(*arrays: np.ndarray) -> np.ndarray:
    if not arrays:
        raise ValueError("At least one array is required.")

    reference_shape = arrays[0].shape

    for array in arrays:
        if array.shape != reference_shape:
            raise ValueError(
                "Input bands must have matching dimensions after alignment."
            )

    mask = np.ones(reference_shape, dtype=bool)

    for array in arrays:
        mask &= np.isfinite(array)

    return mask


def _align_to_reference_grid(
    source_array: np.ndarray,
    source_profile: Dict[str, Any],
    reference_profile: Dict[str, Any],
    target_shape: Tuple[int, int],
    *,
    resampling: str = "bilinear",
) -> np.ndarray:
    """
    Reproject/resample a scientific band onto the reference grid.

    This is used when, for example, Sentinel-2 20 m SWIR is compared with
    Sentinel-2 10 m NIR.

    When both profiles are absent, a shape mismatch is rejected rather than
    silently interpolating an arbitrary array.
    """
    if source_array.shape == target_shape:
        return source_array.astype(np.float32, copy=False)

    if rasterio is None or reproject is None:
        raise RuntimeError(
            "Rasterio is required to align raster bands with different grids."
        )

    required = (
        "transform",
        "crs",
    )
    if not all(source_profile.get(k) for k in required) or not all(
        reference_profile.get(k) for k in required
    ):
        raise ValueError(
            "Bands have different dimensions but lack geospatial transforms/CRS "
            "needed for safe resampling."
        )

    destination = np.full(
        target_shape,
        np.nan,
        dtype=np.float32,
    )

    method = {
        "nearest": Resampling.nearest,
        "bilinear": Resampling.bilinear,
        "cubic": Resampling.cubic,
    }.get(resampling, Resampling.bilinear)

    reproject(
        source=source_array,
        destination=destination,
        src_transform=source_profile["transform"],
        src_crs=source_profile["crs"],
        dst_transform=reference_profile["transform"],
        dst_crs=reference_profile["crs"],
        resampling=method,
        src_nodata=np.nan,
        dst_nodata=np.nan,
    )

    return destination


def _save_georeferenced_mask(
    mask: np.ndarray,
    image: Dict[str, Any],
    prefix: str,
) -> Optional[str]:
    """
    Save an actual georeferenced mask when an output directory is configured.
    """
    output_dir = os.getenv("SATQUERY_MASK_DIR")
    if not output_dir:
        return None

    source = (
        image.get("file_path")
        or image.get("local_path")
        or image.get("image_path")
        or image.get("path")
    )

    if rasterio is None or not source or not os.path.isfile(source):
        return None

    Path(output_dir).mkdir(parents=True, exist_ok=True)

    filename = f"{prefix}_{int(time.time() * 1000)}.tif"
    output_path = Path(output_dir) / filename

    with rasterio.open(source) as src:
        profile = src.profile.copy()
        profile.update(
            {
                "driver": "GTiff",
                "count": 1,
                "dtype": "uint8",
                "nodata": 0,
                "compress": "deflate",
            }
        )

        with rasterio.open(output_path, "w", **profile) as dst:
            dst.write(mask.astype(np.uint8), 1)

    return str(output_path)


# ============================================================
# OPTICAL + SAR FUSION
# ============================================================


class OpticalSARFusionModel(BaseRSModel):
    """
    Optical + SAR multimodal analysis adapter.

    A trained checkpoint is loaded only when SATQUERY_OPTSAR_MODEL_ID is set.
    The model-specific loading and inference remain explicit extension points:
    they cannot honestly be implemented without knowing the checkpoint format.
    """

    MODEL_ENV = "SATQUERY_OPTSAR_MODEL_ID"

    @property
    def name(self) -> str:
        return "OptSAR-Net Multi-Modal Fusion v1.8"

    @property
    def description(self) -> str:
        return (
            "Combines co-registered optical multispectral imagery and SAR "
            "backscatter for multimodal remote-sensing analysis."
        )

    @property
    def supported_input_types(self) -> List[str]:
        return ["optical_sar"]

    @property
    def supported_tasks(self) -> List[str]:
        return ["OPTICAL_SAR_ANALYSIS"]

    @property
    def supports_geotiff(self) -> bool:
        return True

    @property
    def supports_multispectral(self) -> bool:
        return True

    @property
    def supports_sar(self) -> bool:
        return True

    def __init__(self) -> None:
        self.model = None
        self.model_id = os.getenv(self.MODEL_ENV)

    def execute(
        self,
        images: List[Dict[str, Any]],
        query: str,
        metadata: Dict[str, Any],
    ) -> Dict[str, Any]:
        start = time.perf_counter()

        self._validate_inputs(images)

        optical_image = self._find_modality(images, "optical")
        sar_image = self._find_modality(images, "sar")

        if optical_image is None:
            raise ValueError("Optical observation is required.")

        if sar_image is None:
            raise ValueError("SAR observation is required.")

        # Validate that the actual assets can be opened before invoking a
        # configured neural model.
        self._validate_real_assets(
            optical_image,
            role="optical",
        )
        self._validate_real_assets(
            sar_image,
            role="sar",
        )

        if self.model_id:
            try:
                self._ensure_model_loaded()

                result = self._run_fusion(
                    optical_image=optical_image,
                    sar_image=sar_image,
                    query=query,
                    metadata=metadata,
                )

                normalized = self._normalize_result(result)
                normalized.setdefault("execution_details", {})
                normalized["execution_details"].update(
                    {
                        "model_architecture": normalized[
                            "execution_details"
                        ].get("model_architecture", self.name),
                        "model_id": self.model_id,
                        "input_assets": self._asset_summary(
                            optical_image,
                            sar_image,
                        ),
                        "inference_time_ms": round(
                            (time.perf_counter() - start) * 1000,
                            2,
                        ),
                    }
                )

                return normalized

            except NotImplementedError as exc:
                return self._unavailable_result(
                    reason=str(exc),
                    elapsed_ms=(time.perf_counter() - start) * 1000,
                    asset_summary=self._asset_summary(
                        optical_image,
                        sar_image,
                    ),
                )

            except Exception as exc:
                raise RuntimeError(
                    f"Optical-SAR model execution failed: {exc}"
                ) from exc

        return self._unavailable_result(
            reason=(
                "No trained Optical-SAR fusion checkpoint is configured. "
                "Set SATQUERY_OPTSAR_MODEL_ID to enable trained multimodal inference."
            ),
            elapsed_ms=(time.perf_counter() - start) * 1000,
            asset_summary=self._asset_summary(
                optical_image,
                sar_image,
            ),
        )

    def _validate_inputs(
        self,
        images: List[Dict[str, Any]],
    ) -> None:
        if len(images) != 2:
            raise ValueError(
                "Optical-SAR analysis requires exactly two observations."
            )

        if self._find_modality(images, "optical") is None:
            raise ValueError("Optical observation is required.")

        if self._find_modality(images, "sar") is None:
            raise ValueError("SAR observation is required.")

    @staticmethod
    def _find_modality(
        images: List[Dict[str, Any]],
        modality: str,
    ) -> Optional[Dict[str, Any]]:
        for image in images:
            current = _get_modality(image)
            if modality in current:
                return image
        return None

    @staticmethod
    def _validate_real_assets(
        image: Dict[str, Any],
        role: str,
    ) -> None:
        source = image.get("file_path") or image.get("local_path")

        if source and os.path.isfile(source):
            if rasterio is None:
                raise RuntimeError(
                    f"Rasterio is required to validate {role} raster assets."
                )
            with rasterio.open(source) as src:
                if src.width <= 0 or src.height <= 0 or src.count <= 0:
                    raise ValueError(
                        f"The {role} raster has no usable dimensions/bands."
                    )
            return

        # A band map may point to separate real raster files.
        band_map = image.get("band_map")
        if isinstance(band_map, dict):
            paths = []
            for value in band_map.values():
                if isinstance(value, dict) and value.get("path"):
                    paths.append(str(value["path"]))

            if any(os.path.isfile(path) for path in paths):
                return

        raise FileNotFoundError(
            f"No real local {role} raster asset is available."
        )

    @staticmethod
    def _asset_summary(
        optical_image: Dict[str, Any],
        sar_image: Dict[str, Any],
    ) -> Dict[str, Any]:
        return {
            "optical": {
                "file_path": optical_image.get("file_path"),
                "product_id": optical_image.get("product_id"),
                "collection": optical_image.get("collection"),
                "band_map": optical_image.get("band_map"),
            },
            "sar": {
                "file_path": sar_image.get("file_path"),
                "product_id": sar_image.get("product_id"),
                "collection": sar_image.get("collection"),
                "band_map": sar_image.get("band_map"),
            },
        }

    def _ensure_model_loaded(self) -> None:
        if self.model is not None:
            return
        self._load_model()

    def _load_model(self) -> None:
        raise NotImplementedError(
            "Connect _load_model() to the configured trained Optical-SAR "
            f"checkpoint: {self.model_id}. The checkpoint format is not "
            "available to this adapter yet."
        )

    def _run_fusion(
        self,
        optical_image: Dict[str, Any],
        sar_image: Dict[str, Any],
        query: str,
        metadata: Dict[str, Any],
    ) -> Dict[str, Any]:
        if self.model is None:
            raise RuntimeError(
                "Optical-SAR fusion model is not initialized."
            )

        raise NotImplementedError(
            "Implement model-specific Optical-SAR inference in _run_fusion()."
        )

    def _normalize_result(
        self,
        result: Dict[str, Any],
    ) -> Dict[str, Any]:
        if not isinstance(result, dict):
            raise ValueError(
                "Optical-SAR model returned an invalid result."
            )

        normalized = dict(result)
        normalized["confidence"] = _normalize_confidence(
            normalized.get("confidence")
        )
        normalized.setdefault(
            "answer",
            "Optical-SAR analysis completed.",
        )
        normalized.setdefault("visual_evidence", [])
        normalized.setdefault("execution_details", {})
        return normalized

    @staticmethod
    def _unavailable_result(
        reason: str,
        elapsed_ms: float,
        asset_summary: Dict[str, Any],
    ) -> Dict[str, Any]:
        return {
            "answer": (
                "Optical-SAR multimodal analysis could not be executed."
            ),
            "confidence": 0.0,
            "visual_evidence": [],
            "execution_details": {
                "model_architecture": "Unavailable",
                "parameters_used": {},
                "inference_time_ms": round(elapsed_ms, 2),
                "execution_status": "unavailable",
                "reason": reason,
                "input_assets": asset_summary,
            },
        }


# ============================================================
# NDWI WATER DETECTION
# ============================================================


class WaterBodyDetectionTool(BaseRSModel):
    """
    Computes multispectral NDWI directly from real Green/NIR bands.

    Formula:
        NDWI = (Green - NIR) / (Green + NIR)

    Sentinel-2 users normally obtain these from B03 (Green) and B08 (NIR).
    The observation's semantic band map determines the actual files.
    """

    @property
    def name(self) -> str:
        return "Hydro-NDWI Water Segmentation Tool"

    @property
    def description(self) -> str:
        return (
            "Computes NDWI from Green and NIR bands and extracts candidate "
            "water pixels using a configurable threshold."
        )

    @property
    def supported_input_types(self) -> List[str]:
        return ["single_optical", "optical_sar"]

    @property
    def supported_tasks(self) -> List[str]:
        return ["WATER_DETECTION"]

    @property
    def supports_geotiff(self) -> bool:
        return True

    @property
    def supports_multispectral(self) -> bool:
        return True

    def execute(
        self,
        images: List[Dict[str, Any]],
        query: str,
        metadata: Dict[str, Any],
    ) -> Dict[str, Any]:
        start = time.perf_counter()

        if not images:
            raise ValueError(
                "Water detection requires an optical observation."
            )

        image = self._select_optical_image(images)

        green, green_profile = _read_semantic_band_with_profile(
            image,
            metadata,
            "green",
        )
        nir, nir_profile = _read_semantic_band_with_profile(
            image,
            metadata,
            "nir",
        )

        # Align NIR onto Green's grid only when actual geospatial metadata is
        # available. This avoids the old silent resize/crop behavior.
        nir = _align_to_reference_grid(
            nir,
            nir_profile,
            green_profile,
            green.shape,
        )

        threshold = self._get_threshold(metadata)
        ndwi = self._calculate_ndwi(green, nir)
        valid_mask = _get_valid_data_mask(green, nir)
        water_mask = (ndwi >= threshold) & valid_mask

        valid_ndwi = ndwi[valid_mask]
        valid_count = int(np.count_nonzero(valid_mask))
        water_count = int(np.count_nonzero(water_mask))

        water_percentage = (
            float(water_count / valid_count * 100.0)
            if valid_count
            else 0.0
        )

        statistics = _safe_statistics(valid_ndwi)
        elapsed_ms = (time.perf_counter() - start) * 1000

        overlay_url = self._save_overlay(
            water_mask,
            image,
            prefix="ndwi_water",
        )

        return {
            "answer": (
                "NDWI water extraction completed. "
                f"{water_percentage:.2f}% of the valid analysed pixels "
                f"exceed the configured threshold of {threshold:.3f}."
            ),
            "confidence": 0.0,
            "visual_evidence": {
                "overlay_type": "water_mask",
                "label": "NDWI Spectral Water Mask",
                "mask_url": overlay_url,
                "statistics": {
                    "water_pixel_percentage": water_percentage,
                    "valid_pixel_percentage": (
                        float(valid_count / valid_mask.size * 100.0)
                        if valid_mask.size
                        else 0.0
                    ),
                    "threshold": threshold,
                    "ndwi_min": statistics["min"],
                    "ndwi_max": statistics["max"],
                    "ndwi_mean": statistics["mean"],
                },
            },
            "execution_details": {
                "model_architecture": (
                    "NDWI Spectral Index + Configurable Threshold"
                ),
                "inference_time_ms": round(elapsed_ms, 2),
                "execution_status": "completed",
                "parameters_used": {
                    "ndwi_formula": "(Green - NIR) / (Green + NIR)",
                    "threshold": threshold,
                    "green_band": "green",
                    "nir_band": "nir",
                },
                "confidence_note": (
                    "NDWI is deterministic; confidence 0 indicates that "
                    "no calibrated probabilistic confidence is supplied."
                ),
            },
        }

    @staticmethod
    def _select_optical_image(
        images: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        for image in images:
            if _is_optical(image):
                return image

        raise ValueError(
            "An optical or multispectral observation is required for NDWI analysis."
        )

    @staticmethod
    def _calculate_ndwi(
        green: np.ndarray,
        nir: np.ndarray,
    ) -> np.ndarray:
        denominator = green + nir

        return np.divide(
            green - nir,
            denominator,
            out=np.full_like(green, np.nan, dtype=np.float32),
            where=np.abs(denominator) > 1e-8,
        )

    @staticmethod
    def _get_threshold(
        metadata: Dict[str, Any],
    ) -> float:
        value = metadata.get("ndwi_threshold")

        if value is None:
            value = os.getenv(
                "SATQUERY_NDWI_THRESHOLD",
                "0.30",
            )

        try:
            numeric = float(value)
        except (TypeError, ValueError):
            numeric = 0.30

        if not -1.0 <= numeric <= 1.0:
            raise ValueError(
                "NDWI threshold must be between -1 and 1."
            )

        return numeric

    @staticmethod
    def _save_overlay(
        mask: np.ndarray,
        image: Dict[str, Any],
        prefix: str,
    ) -> Optional[str]:
        return _save_georeferenced_mask(
            mask,
            image,
            prefix,
        )


# ============================================================
# NDBI BUILT-UP DETECTION
# ============================================================


class BuiltUpAreaDetectionTool(BaseRSModel):
    """
    Computes NDBI directly from real SWIR1/NIR bands.

    Formula:
        NDBI = (SWIR1 - NIR) / (SWIR1 + NIR)

    Sentinel-2 users normally obtain SWIR1 from B11 and NIR from B08.
    """

    @property
    def name(self) -> str:
        return "Urban-NDBI Built-Up Detector"

    @property
    def description(self) -> str:
        return (
            "Computes NDBI from SWIR1 and NIR optical bands and extracts "
            "candidate built-up pixels using a configurable threshold."
        )

    @property
    def supported_input_types(self) -> List[str]:
        return ["single_optical", "optical_sar"]

    @property
    def supported_tasks(self) -> List[str]:
        return ["BUILT_UP_ANALYSIS"]

    @property
    def supports_geotiff(self) -> bool:
        return True

    @property
    def supports_multispectral(self) -> bool:
        return True

    def execute(
        self,
        images: List[Dict[str, Any]],
        query: str,
        metadata: Dict[str, Any],
    ) -> Dict[str, Any]:
        start = time.perf_counter()

        if not images:
            raise ValueError(
                "Built-up analysis requires an optical observation."
            )

        image = self._select_optical_image(images)

        swir, swir_profile = _read_semantic_band_with_profile(
            image,
            metadata,
            "swir1",
        )
        nir, nir_profile = _read_semantic_band_with_profile(
            image,
            metadata,
            "nir",
        )

        # Sentinel-2 SWIR1 is normally 20 m while NIR is 10 m. When the
        # ingested assets retain their native files, align SWIR to the NIR grid
        # using actual CRS/transform metadata.
        swir = _align_to_reference_grid(
            swir,
            swir_profile,
            nir_profile,
            nir.shape,
        )

        threshold = self._get_threshold(metadata)
        ndbi = self._calculate_ndbi(swir, nir)

        valid_mask = _get_valid_data_mask(swir, nir)
        builtup_mask = (ndbi >= threshold) & valid_mask

        valid_count = int(np.count_nonzero(valid_mask))
        builtup_count = int(np.count_nonzero(builtup_mask))

        builtup_percentage = (
            float(builtup_count / valid_count * 100.0)
            if valid_count
            else 0.0
        )

        statistics = _safe_statistics(ndbi[valid_mask])
        elapsed_ms = (time.perf_counter() - start) * 1000

        overlay_url = self._save_overlay(
            builtup_mask,
            image,
            prefix="ndbi_builtup",
        )

        return {
            "answer": (
                "NDBI built-up extraction completed. "
                f"{builtup_percentage:.2f}% of valid analysed pixels "
                f"exceed the configured threshold of {threshold:.3f}."
            ),
            "confidence": 0.0,
            "visual_evidence": {
                "overlay_type": "builtup_mask",
                "label": "NDBI Built-Up Candidate Mask",
                "mask_url": overlay_url,
                "statistics": {
                    "builtup_pixel_percentage": builtup_percentage,
                    "valid_pixel_percentage": (
                        float(valid_count / valid_mask.size * 100.0)
                        if valid_mask.size
                        else 0.0
                    ),
                    "threshold": threshold,
                    "ndbi_min": statistics["min"],
                    "ndbi_max": statistics["max"],
                    "ndbi_mean": statistics["mean"],
                },
            },
            "execution_details": {
                "model_architecture": (
                    "NDBI Spectral Index + Configurable Threshold"
                ),
                "inference_time_ms": round(elapsed_ms, 2),
                "execution_status": "completed",
                "parameters_used": {
                    "ndbi_formula": "(SWIR1 - NIR) / (SWIR1 + NIR)",
                    "threshold": threshold,
                    "swir_band": "swir1",
                    "nir_band": "nir",
                },
                "confidence_note": (
                    "NDBI is deterministic; confidence 0 indicates that "
                    "no calibrated probabilistic confidence is supplied."
                ),
            },
        }

    @staticmethod
    def _select_optical_image(
        images: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        for image in images:
            if _is_optical(image):
                return image

        raise ValueError(
            "An optical or multispectral observation is required for NDBI analysis."
        )

    @staticmethod
    def _calculate_ndbi(
        swir: np.ndarray,
        nir: np.ndarray,
    ) -> np.ndarray:
        denominator = swir + nir

        return np.divide(
            swir - nir,
            denominator,
            out=np.full_like(swir, np.nan, dtype=np.float32),
            where=np.abs(denominator) > 1e-8,
        )

    @staticmethod
    def _get_threshold(
        metadata: Dict[str, Any],
    ) -> float:
        value = metadata.get("ndbi_threshold")

        if value is None:
            value = os.getenv(
                "SATQUERY_NDBI_THRESHOLD",
                "0.20",
            )

        try:
            numeric = float(value)
        except (TypeError, ValueError):
            numeric = 0.20

        if not -1.0 <= numeric <= 1.0:
            raise ValueError(
                "NDBI threshold must be between -1 and 1."
            )

        return numeric

    @staticmethod
    def _save_overlay(
        mask: np.ndarray,
        image: Dict[str, Any],
        prefix: str,
    ) -> Optional[str]:
        return _save_georeferenced_mask(
            mask,
            image,
            prefix,
        )
